
  get  https://api.spotify.com/v1/search?q=artist:draganov&type=track  HTTP/1.1
Content-Type: application/json
Authorization: Bearer BQByDS1hfT1LsIYQO1besx-i5esr5vS1u82I0pf501uIDiMyM6YalRB2Vo-aoXOjxZ_4Q5rLUWKmQgwgipFGqgENNY3TPQakBWpJoMwW60IyYVF3LHxb
###


 {/* { tracks.forEach((track) => {
      const albumName = track.album.name;
      const releaseDate = track.album.release_date;
      const artistNames = track.artists.map((artist) => artist.name);

      // Do something with the extracted data
      console.log(`Album: ${albumName}`);
      console.log(`Release Date: ${releaseDate}`);
      console.log(`Artists: ${artistNames.join(", ")}`);
    })} */}
       {/* <tr>
          <td>{album.name}</td>
          <td>{artists[0].name}</td>
          <td>{name}</td>
          <td>{duration_ms}</td>
          <td>{popularity}</td>
        </tr> */


