get https://api.spotify.com/v1/search?q=artist:adele&type=track HTTP/1.1
 
  "headers": 
     "Authorization":"Bearer BQDqz3yYJYKTnXYcXcR7glGp9sglDKeKMZNy0jfq9jGTYWvd13t1wSvC0s1CSAyTmtZVvG41YLR1SjJY8Ell5zvM4vP6GhZlGBDzPo4C51zwnsRRTic5"
  
###
  GET https://api.spotify.com/v1/search?q=artist:adele&type=track  HTTP/1.1
Authorization: Bearer BQDqz3yYJYKTnXYcXcR7glGp9sglDKeKMZNy0jfq9jGTYWvd13t1wSvC0s1CSAyTmtZVvG41YLR1SjJY8Ell5zvM4vP6GhZlGBDzPo4C51zwnsRRTic5